# language: en

@landing
Feature: Landing Page informational sections

As a Landing Page visitor
I want to review CampusLink's main informational sections
So that I can understand the value proposition, the problem, the solution, how it works, the benefits, the target users, the responsive adaptation, and the institutional closing of the product.

@US51 @automated
Scenario: US51 - Scenario 1: Successful display of the value proposition
Given the visitor enters the CampusLink Landing Page
When the site's initial section loads
Then the system shows the main title, a description of CampusLink, and a representative image of the product

@US51 @automated
Scenario: US51 - Scenario 2: Quick understanding of the product's purpose
Given the visitor views the Landing Page's main section
When they read CampusLink's introductory message
Then the system communicates that CampusLink allows reporting, locating, and tracking campus incidents

@US51 @automated
Scenario: US51 - Scenario 3: Initial access to the Landing Page's main actions
Given the visitor is on the Landing Page's initial section
When they review the Hero's visible elements
Then the system shows entry points or calls to action related to learning about the product or starting to browse the page

@US53 @automated
Scenario: US53 - Scenario 1: Display of the current problem
Given the visitor navigates to the "Problem" section
When they review the content presented about the current situation
Then the system shows the main problems that CampusLink seeks to solve

@US53 @automated
Scenario: US53 - Scenario 2: Identifying difficulties in incident management
Given the visitor is on the "Problem" section
When they review the problem's informational cards
Then the system presents difficulties such as scattered reports, lack of follow-up, and incomplete information for support

@US53 @automated
Scenario: US53 - Scenario 3: Relating the problem to the campus's need
Given the visitor analyzes the "Problem" section
When they compare the information presented with the experience of reporting incidents on a campus
Then the system helps them understand the need to centralize incident reporting

@US54 @automated
Scenario: US54 - Scenario 1: Display of the proposed solution
Given the visitor navigates to the "Solution" section
When they review the content presented about CampusLink
Then the system shows how CampusLink helps report, locate, and track incidents

@US54 @automated
Scenario: US54 - Scenario 2: Identifying the solution's main components
Given the visitor is on the "Solution" section
When they review the solution's informational cards
Then the system presents components such as fast reporting, precise location, clear evidence, and visible tracking

@US54 @automated
Scenario: US54 - Scenario 3: Understanding CampusLink's differential value
Given the visitor analyzes the "Solution" section
When they interpret the information presented
Then the system communicates that CampusLink centralizes the campus incident reporting and tracking process

@US55 @automated
Scenario: US55 - Scenario 1: Display of the how-it-works flow
Given the visitor accesses the "How it works" section
When they review the steps presented
Then the system shows a clear sequence of the incident reporting and tracking process

@US55 @automated
Scenario: US55 - Scenario 2: Understanding the reporting process
Given the visitor is on the "How it works" section
When they review CampusLink's usage journey
Then the system explains that the user detects an incident, scans a QR code, records evidence, and sends the report to support

@US55 @automated
Scenario: US55 - Scenario 3: Relating the process steps to report tracking
Given the visitor analyzes the "How it works" section
When they view the complete how-it-works sequence
Then the system communicates that the report can be received, handled, and tracked by the user

@US56 @automated
Scenario: US56 - Scenario 1: Successful display of benefits
Given the visitor accesses the "Benefits" section
When they review the informational cards
Then the system shows the main benefits generated by CampusLink

@US56 @automated
Scenario: US56 - Scenario 2: Identifying operational benefits
Given the visitor is on the "Benefits" section
When they review the benefits presented
Then the system highlights benefits such as fast reporting, precise location, clear evidence, transparent tracking, and operational prioritization

@US56 @automated
Scenario: US56 - Scenario 3: Understanding the impact of the benefits
Given the visitor analyzes the "Benefits" section
When they relate the benefits to campus incident management
Then the system helps them understand how CampusLink improves communication between users and support

@US57 @automated
Scenario: US57 - Scenario 1: Display of target users
Given the visitor accesses the "Who it is for" section
When they review the profile cards
Then the system shows students, teachers, and support or operations staff as target users

@US57 @automated
Scenario: US57 - Scenario 2: Understanding the value for students and teachers
Given the visitor is on the "Who it is for" section
When they review the student and teacher profiles
Then the system communicates that both profiles can report incidents and track their requests

@US57 @automated
Scenario: US57 - Scenario 3: Understanding the value for support and operations
Given the visitor analyzes the "Who it is for" section
When they review the support or operations staff profile
Then the system communicates that this profile can receive clearer information to handle incidents

@US60 @automated
Scenario: US60 - Scenario 1: Responsive display of the Landing Page
Given the visitor opens the Landing Page from a mobile screen
When they navigate through the site's main sections
Then the system adapts text, images, cards, and navigation to the screen size

@US60 @automated
Scenario: US60 - Scenario 2: Reading content on mobile devices
Given the visitor reviews the Landing Page from a mobile device
When they view the informational sections
Then the system keeps the content readable and organized without causing unnecessary horizontal scrolling

@US60 @automated
Scenario: US60 - Scenario 3: Responsive access to main sections
Given the visitor uses the mobile version of the Landing Page
When they interact with the site's navigation and sections
Then the system allows access to the main content without losing information

@US62 @automated
Scenario: US62 - Scenario 1: Display of the footer
Given the visitor reaches the end of the Landing Page
When they view the final section
Then the system shows the CampusLink logo or name and a closing message

@US62 @automated
Scenario: US62 - Scenario 2: Recognizing the responsible team
Given the visitor is on the Landing Page's footer
When they review the final institutional information
Then the system shows the reference to the Montimin team as the product's owner

@US62 @automated
Scenario: US62 - Scenario 3: Institutional closing of the Landing Page
Given the visitor analyzes the Landing Page's closing
When they read the site's final message
Then the system reinforces that CampusLink brings together campus incident reporting, location, evidence, and tracking in one place
